version: "3"

services:
  #region HDFS
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    command: bash /home/hdfs_data_import/run_namenode.sh
    tty: true
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - hadoop_nn:/hadoop/dfs/name
      - ../local_data:/home/data
      - ../hdfs_data_import:/home/hdfs_data_import
    environment:
      - CLUSTER_NAME=hdfs_cluster
    env_file:
      - ./hdfs.env

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1
    volumes:
      - hadoop_dn1:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hdfs.env
  #end-region HDFS

  #region SPARK
  spark-master:
    image: bde2020/spark-master:3.0.1-hadoop3.2
    container_name: spark-master
    command: bash /home/spark_automatic_run/spark_run.sh
    ports:
      - 8080:8080
      - 7077:7077
    environment: 
      - PYSPARK_PYTHON=python3
    env_file:
      - ./hdfs.env
    volumes: 
      - ../spark/spark_batch:/home/spark_batch
      - ../spark/spark_stream/spark_streaming_consumer:/home/spark_stream
      - ../spark/spark_automatic_run:/home/spark_automatic_run

  spark-worker1:
    image: bde2020/spark-worker:3.0.1-hadoop3.2
    container_name: spark-worker1
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    ports:
      - 8081:8081
    env_file:
      - ./hdfs.env
  #end-region SPARK

  #region ZOOKEEPER
  zoo1:
    image: zookeeper:3.4.9
    container_name: zoo1
    ports:
      - "2181:2181"
    environment:
        ZOO_MY_ID: 1
        ZOO_PORT: 2181
        ZOO_SERVERS: server.1=zoo1:2888:3888
    volumes:
      - zoo1:/data
      - zoo1log:/datalog
  #end-region ZOOKEEPER

  #region KAFKA
  kafka1:
    image: confluentinc/cp-kafka:5.3.1
    container_name: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
    volumes:
      - kafka1:/var/lib/kafka/data
    depends_on:
      - zoo1
  #end-region KAFKA

  #region MONGODB
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - mongodb:/data/db
    ports:
      - "27017:27017"
    expose:
      - "27017"

  mongodb2:
    image: mongo
    container_name: mongodb2
    volumes:
      - mongodb2:/data/db
    ports:
      - "27018:27017"
    expose:
      - "27018"
  #end region MONGODB

  #region METABASE
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    volumes: 
     - metabase:/metabase-data  
    ports:
     - "3000:3000"
  #end region METABASE

  #region SPARK STRUCTURED STREAMING
  producer1:
    build: ../spark/spark_stream/kafka_producer
    container_name: kafka_producer
    command: python3 /home/producer/twitter_producer.py
    environment:
      KAFKA_BROKER: "kafka1:19092"
    env_file:
      - ../spark/spark_stream/spark_stream.env
    depends_on:
      - kafka1
    volumes:
      - ../spark/spark_stream/kafka_producer/producer:/home/producer
  #end region SPARK STRUCTURED STREAMING

volumes:
  hadoop_nn:
  hadoop_dn1:
  zoo1:
  zoo1log:
  kafka1:
  mongodb:
  mongodb2:
  metabase:
